### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by condemnedmeat** [djrscally/miix-510-cameras#9]
> My wife just had a baby

Congratulations! :baby: :tada: 

As you mentioned it I thought it would be impolite not to say something.

In this context your efforts are all the more superb so thank you. 2020 lookin' pretty good for you!

Mark

************************************

I'm sorry for the issues abuse, I did look around to see if it was possible to contact you in a more discreet way. I'll delete the content immediately so it doesn't stick out. I assume you get it by email.

**Comment by djrscally** [comment]
Thanks dude, much appreciated - I did indeed get the notification. Might  mean a slight slow down in productivity for a while but I'm hoping to get back up to speed before too long!
